# Use the PGPv3 6G core
export INCLUDE_PGP3_6G = 1

# Define the firmware version
export PRJ_VERSION = 0x00000026

# Define target output
target: prom

# Define target part
export PRJ_PART = XC7K160TFBG484-2

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
