# define firmware version
export PRJ_VERSION = 0x00000002

# Define target output
target: bit

# Define target part
export PRJ_PART = XC7Z030FBG484-2

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
