
// Generated by Cadence Encounter(R) RTL Compiler RC14.27 - v14.20-s064_1

// Verification Directory fv/LTMR2 

module LTMR_DFQD(CP, D, Q);
  input CP, D;
  output Q;
  wire CP, D1, D2, D3;
  wire Q;
  wire Q1, Q2, Q3;
  wire n_0;
  DFQD1 dreg1(.CP (CP), .D (D), .Q (Q2));
  DFQD1 dreg2(.CP (CP), .D (D), .Q (Q1));
  DFQD1 dreg3(.CP (CP), .D (D), .Q (Q3));
  MAOI222D0 p4324D(.A (Q1), .B (Q2), .C (Q3), .ZN (n_0));
  CKND0 Fp4461A(.I (n_0), .ZN (Q));
endmodule

