# Define the firmware version
export PRJ_VERSION = 0x00000032

# Define target output
target: prom

# Define target part
export PRJ_PART = XC7K160TFBG484-2

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
