export GIT_BYPASS = 1

# Use the PGPv3 10G core
export INCLUDE_PGP3_10G = 1

# Define the firmware version
export PRJ_VERSION = 0x00000001

# Define target output
target: prom

# Define target part
export PRJ_PART = XC7K160TFBG484-2

# Use top level makefile
include ../../submodules/ruckus/system_vivado.mk
