
/*   AUTOMATICALLY GENERATED BY NC-Verilog - DO NOT EDIT   */

// Verilog HDL and netlist files of
// "RD53_SER_CML_Bonn Serializer_TapDelayX4 schematic"


// Netlisted models

// Library - RD53_SER_CML_Bonn, Cell - Buff_Tree, View - schematic
// LAST TIME SAVED: Mar  2 19:11:26 2017
// NETLIST TIME: Mar 21 20:07:23 2017
`timescale 1ns / 1ps 

module Buff_Tree ( Buff, Buff11, Buff12, OUT0, OUT1, OUT2, OUT3, VDD, VSS, IN );

output  Buff, Buff11, Buff12, OUT0, OUT1, OUT2, OUT3;

inout  VDD, VSS;

input  IN;

// List of primary aliased buses


specify 
    specparam CDS_LIBNAME  = "RD53_SER_CML_Bonn";
    specparam CDS_CELLNAME = "Buff_Tree";
    specparam CDS_VIEWNAME = "schematic";
endspecify

INVD24 I23 ( net10, OUT0, VDD, VSS);
INVD24 I22 ( Buff11, net10, VDD, VSS);
INVD24 I15 ( net14, Buff11, VDD, VSS);
INVD24 I14 ( Buff, net14, VDD, VSS);
INVD24 I21 ( Buff11, net9, VDD, VSS);
INVD24 I20 ( net9, OUT1, VDD, VSS);
INVD24 I11 ( net15, Buff, VDD, VSS);
INVD24 I10 ( net16, net15, VDD, VSS);
INVD24 I27 ( Buff12, net12, VDD, VSS);
INVD24 I28 ( net12, OUT2, VDD, VSS);
INVD24 I17 ( Buff, net13, VDD, VSS);
INVD24 I16 ( net13, Buff12, VDD, VSS);
INVD24 I26 ( Buff12, net11, VDD, VSS);
INVD24 I25 ( net11, OUT3, VDD, VSS);
INVD8 I7 ( net17, net16, VDD, VSS);
INVD8 I5 ( IN, net17, VDD, VSS);

endmodule
// Library - RD53_SER_CML_Bonn, Cell - LFSR7, View - schematic
// LAST TIME SAVED: Mar 15 14:55:54 2017
// NETLIST TIME: Mar 21 20:07:24 2017
`timescale 1ns / 1ps 

module LFSR7 ( OUT, VDD, VSS, CLK, RST_B );

output  OUT;

inout  VDD, VSS;

input  CLK, RST_B;

// Buses in the design

wire  [0:6]  BIT;

// List of primary aliased buses


specify 
    specparam CDS_LIBNAME  = "RD53_SER_CML_Bonn";
    specparam CDS_CELLNAME = "LFSR7";
    specparam CDS_VIEWNAME = "schematic";
endspecify

XNR2D4 I12 ( BIT[5], BIT[6], net8, VDD, VSS);
DFCNQD4 I198 ( net8, CLK_B, RST_B, BIT[0], VDD, VSS);
DFCNQD4 I17 ( BIT[0], CLK_B, RST_B, BIT[1], VDD, VSS);
DFCNQD4 I20 ( BIT[3], CLK_B, RST_B, BIT[4], VDD, VSS);
DFCNQD4 I19 ( BIT[2], CLK_B, RST_B, BIT[3], VDD, VSS);
DFCNQD4 I22 ( BIT[5], CLK_B, RST_B, BIT[6], VDD, VSS);
DFCNQD4 I21 ( BIT[4], CLK_B, RST_B, BIT[5], VDD, VSS);
DFCNQD4 I18 ( BIT[1], CLK_B, RST_B, BIT[2], VDD, VSS);
CKND6 I24 ( CLK, CLK_B, VDD, VSS);
CKND6 I68 ( BIT[6], OUT, VDD, VSS);

endmodule
// Library - RD53_SER_CML_Bonn, Cell - Ser_20to1, View - schematic
// LAST TIME SAVED: Mar 15 14:55:59 2017
// NETLIST TIME: Mar 21 20:07:24 2017
`timescale 1ns / 1ps 

module Ser_20to1 ( CLK_INT, LOAD_INT_B, OUT, VDD, VSS, CLK, IN, LOAD );

output  CLK_INT, LOAD_INT_B, OUT;

inout  VDD, VSS;

input  CLK, LOAD;

input [19:0]  IN;

// Buses in the design

wire  [0:19]  Q;

wire  [18:19]  D;

// List of primary aliased buses


specify 
    specparam CDS_LIBNAME  = "RD53_SER_CML_Bonn";
    specparam CDS_CELLNAME = "Ser_20to1";
    specparam CDS_VIEWNAME = "schematic";
endspecify

INVD4 I355 ( LOAD_INT_B, net053, VDD, VSS);
INVD4 I358 ( LOAD_INT_B, net052, VDD, VSS);
DCAP4 I377 ( VDD, VSS);
CKBD16 I417 ( net013, net014, VDD, VSS);
INVD24 I361 ( LOAD, LOAD_INT_B, VDD, VSS);
CKND4 I420 ( MX_OUT, net05, VDD, VSS);
DFXQD4 I413 ( .CP(CLK_INT), .Q(Q[12]), .SA(LOAD_INT_B),
     .DA(Q[14]), .DB(IN[12]), .VDD(VDD), .VSS(VSS));
DFXQD4 I411 ( .CP(CLK_INT), .Q(Q[8]), .SA(LOAD_INT_B),
     .DA(Q[10]), .DB(IN[8]), .VDD(VDD), .VSS(VSS));
DFXQD4 I410 ( .CP(CLK_INT), .Q(Q[6]), .SA(LOAD_INT_B),
     .DA(Q[8]), .DB(IN[6]), .VDD(VDD), .VSS(VSS));
DFXQD4 I409 ( .CP(CLK_INT), .Q(Q[4]), .SA(LOAD_INT_B),
     .DA(Q[6]), .DB(IN[4]), .VDD(VDD), .VSS(VSS));
DFXQD4 I408 ( .CP(CLK_INT), .Q(Q[2]), .SA(LOAD_INT_B),
     .DA(Q[4]), .DB(IN[2]), .VDD(VDD), .VSS(VSS));
DFXQD4 I381 ( .CP(CLK_INT), .Q(Q[17]), .SA(LOAD_INT_B),
     .DA(Q[19]), .DB(IN[17]), .VDD(VDD), .VSS(VSS));
DFXQD4 I406 ( .CP(CLK_INT), .Q(Q[1]), .SA(LOAD_INT_B),
     .DA(Q[3]), .DB(IN[1]), .VDD(VDD), .VSS(VSS));
DFXQD4 I412 ( .CP(CLK_INT), .Q(Q[10]), .SA(LOAD_INT_B),
     .DA(Q[12]), .DB(IN[10]), .VDD(VDD), .VSS(VSS));
DFXQD4 I405 ( .CP(CLK_INT), .Q(Q[3]), .SA(LOAD_INT_B),
     .DA(Q[5]), .DB(IN[3]), .VDD(VDD), .VSS(VSS));
DFXQD4 I404 ( .CP(CLK_INT), .Q(Q[5]), .SA(LOAD_INT_B),
     .DA(Q[7]), .DB(IN[5]), .VDD(VDD), .VSS(VSS));
DFXQD4 I403 ( .CP(CLK_INT), .Q(Q[7]), .SA(LOAD_INT_B),
     .DA(Q[9]), .DB(IN[7]), .VDD(VDD), .VSS(VSS));
DFXQD4 I402 ( .CP(CLK_INT), .Q(Q[9]), .SA(LOAD_INT_B),
     .DA(Q[11]), .DB(IN[9]), .VDD(VDD), .VSS(VSS));
DFXQD4 I401 ( .CP(CLK_INT), .Q(Q[11]), .SA(LOAD_INT_B),
     .DA(Q[13]), .DB(IN[11]), .VDD(VDD), .VSS(VSS));
DFXQD4 I400 ( .CP(CLK_INT), .Q(Q[13]), .SA(LOAD_INT_B),
     .DA(Q[15]), .DB(IN[13]), .VDD(VDD), .VSS(VSS));
DFXQD4 I414 ( .CP(CLK_INT), .Q(Q[14]), .SA(LOAD_INT_B),
     .DA(Q[16]), .DB(IN[14]), .VDD(VDD), .VSS(VSS));
DFXQD4 I399 ( .CP(CLK_INT), .Q(Q[15]), .SA(LOAD_INT_B),
     .DA(Q[17]), .DB(IN[15]), .VDD(VDD), .VSS(VSS));
DFXQD4 I407 ( .CP(CLK_INT), .Q(Q[0]), .SA(LOAD_INT_B),
     .DA(Q[2]), .DB(IN[0]), .VDD(VDD), .VSS(VSS));
DFXQD4 I415 ( .CP(CLK_INT), .Q(Q[16]), .SA(LOAD_INT_B),
     .DA(Q[18]), .DB(IN[16]), .VDD(VDD), .VSS(VSS));
MUX2D4 I315 ( .S(CLK_INT), .I1(LATCH_OUT), .I0(Q[0]),
     .Z(MX_OUT), .VDD(VDD), .VSS(VSS));
CKBD24 I418 ( net014, net011, VDD, VSS);
CKND24 I419 ( net011, CLK_INT, VDD, VSS);
DCAP I376 ( VDD, VSS);
LNQD4 I314 ( .EN(CLK_INT), .D(Q[1]), .Q(LATCH_OUT), .VSS(VSS),
     .VDD(VDD));
DFQD4 I360 ( .CP(CLK_INT), .D(D[18]), .Q(Q[18]), .VDD(VDD),
     .VSS(VSS));
DFQD4 I357 ( .CP(CLK_INT), .D(D[19]), .Q(Q[19]), .VDD(VDD),
     .VSS(VSS));
DCAP16 I375 ( VDD, VSS);
AN2D4 I359 ( IN[18], net052, D[18], VDD, VSS);
AN2D4 I356 ( IN[19], net053, D[19], VDD, VSS);
CKBD8 I416 ( CLK, net013, VDD, VSS);
CKND8 I421 ( net05, OUT, VDD, VSS);

endmodule
// Library - RD53_SER_CML_Bonn, Cell - Serializer, View - schematic
// LAST TIME SAVED: Mar 15 14:56:07 2017
// NETLIST TIME: Mar 21 20:07:24 2017
`timescale 1ns / 1ps 

module Serializer ( CLK_640_INT, CLK_TAP, D_OUT, LOAD_INT_B, VDD, VSS,
     CLK_64, CLK_640, DATA, EXT_RST_B, LOAD, SER_CLK, SER_SEL_OUT );

output  CLK_640_INT, CLK_TAP, D_OUT, LOAD_INT_B;

inout  VDD, VSS;

input  CLK_64, CLK_640, EXT_RST_B, LOAD, SER_CLK;

input [19:0]  DATA;
input [1:0]  SER_SEL_OUT;

// Buses in the design

wire  [19:0]  IN_SAMPLED;

// List of primary aliased buses


specify 
    specparam CDS_LIBNAME  = "RD53_SER_CML_Bonn";
    specparam CDS_CELLNAME = "Serializer";
    specparam CDS_VIEWNAME = "schematic";
endspecify

LFSR7 LFSR7 ( .VDD(VDD), .VSS(VSS), .OUT(LFSR7_OUT), .CLK(CLK_TAP),
     .RST_B(EXT_RST_LFSR7_B));
Ser_20to1 Ser ( .LOAD_INT_B(LOAD_INT_B), .CLK_INT(CLK_640_INT),
     .CLK(CLK_640), .VDD(VDD), .IN(IN_SAMPLED[19:0]), .LOAD(LOAD),
     .VSS(VSS), .OUT(SER_OUT));
CKBD24 I418 ( net012, net011, VDD, VSS);
CKBD8 I416 ( SER_CLK, net013, VDD, VSS);
CKND8 I37 ( EXT_RST_B, EXT_RST_LFSR7_B, VDD, VSS);
MUX4D4 Mux ( .S1(SER_SEL_OUT[1]), .S0(SER_SEL_OUT[0]),
     .I3(tieL), .I2(SER_OUT), .I1(LFSR7_OUT), .I0(CLK_640_INT),
     .Z(net06), .VSS(VSS), .VDD(VDD));
CKBD16 I417 ( net013, net012, VDD, VSS);
CKBD16 I36 ( net06, D_OUT, VDD, VSS);
DFQD4 DF[19:0] ( .Q(IN_SAMPLED[19:0]), .VDD(VDD), .VSS(VSS),
     .CP(CLK_64), .D(DATA[19:0]));
CKND24 I419 ( net011, CLK_TAP, VDD, VSS);
TIEL I3 ( tieL, VDD, VSS);

endmodule
// Library - RD53_SER_CML_Bonn, Cell - DelayTap, View - schematic
// LAST TIME SAVED: Mar 15 14:56:06 2017
// NETLIST TIME: Mar 21 20:07:24 2017
`timescale 1ns / 1ps 

module DelayTap ( TAP1, TAP2, TAP3, VDD, VSS, CLK_TAP, D, EN_TAP,
     INV_TAP );

output  TAP1, TAP2, TAP3;

inout  VDD, VSS;

input  CLK_TAP, D;

input [2:1]  INV_TAP;
input [2:1]  EN_TAP;

// List of primary aliased buses


specify 
    specparam CDS_LIBNAME  = "RD53_SER_CML_Bonn";
    specparam CDS_CELLNAME = "DelayTap";
    specparam CDS_VIEWNAME = "schematic";
endspecify

MUX2D4 I26 ( .S(INV_TAP[2]), .I1(DN3), .I0(TAP3), .Z(net014),
     .VDD(VDD), .VSS(VSS));
MUX2D4 I35 ( .S(EN_TAP[2]), .I1(net025), .I0(net019),
     .Z(net020), .VDD(VDD), .VSS(VSS));
MUX2D4 I22 ( .S(INV_TAP[2]), .I1(DN2), .I0(TAP2), .Z(net019),
     .VDD(VDD), .VSS(VSS));
MUX2D4 I33 ( .S(EN_TAP[1]), .I1(net016), .I0(net013),
     .Z(net017), .VDD(VDD), .VSS(VSS));
MUX2D4 I2 ( .S(INV_TAP[1]), .I1(DN1), .I0(TAP1), .Z(net013),
     .VDD(VDD), .VSS(VSS));
DFD4 I21 ( net017, CLK_TAP, TAP2, DN2, VDD, VSS);
DFD4 I23 ( net020, CLK_TAP, TAP3, DN3, VDD, VSS);
DFD4 I20 ( D, CLK_TAP, TAP1, DN1, VDD, VSS);
TIEL I34 ( net025, VDD, VSS);
TIEL I32 ( net016, VDD, VSS);

endmodule
// Library - RD53_SER_CML_Bonn, Cell - Serializer_TapDelay, View -
//schematic
// LAST TIME SAVED: Mar 15 14:55:56 2017
// NETLIST TIME: Mar 21 20:07:24 2017
`timescale 1ns / 1ps 

module Serializer_TapDelay ( CLK_640_INT, LOAD_INT_B, TAP1, TAP2, TAP3,
     VDD, VSS, CLK_64, CLK_640, DATA, EN_TAP, EXT_RST_B, INV_TAP, LOAD,
     SER_CLK, SER_SEL_OUT );

output  CLK_640_INT, LOAD_INT_B, TAP1, TAP2, TAP3;

inout  VDD, VSS;

input  CLK_64, CLK_640, EXT_RST_B, LOAD, SER_CLK;

input [19:0]  DATA;
input [2:1]  INV_TAP;
input [1:0]  SER_SEL_OUT;
input [2:1]  EN_TAP;

// List of primary aliased buses


specify 
    specparam CDS_LIBNAME  = "RD53_SER_CML_Bonn";
    specparam CDS_CELLNAME = "Serializer_TapDelay";
    specparam CDS_VIEWNAME = "schematic";
endspecify

Serializer I0 ( .CLK_640_INT(CLK_640_INT),
     .SER_SEL_OUT(SER_SEL_OUT[1:0]), .DATA(DATA[19:0]),
     .SER_CLK(SER_CLK), .CLK_640(CLK_640), .CLK_64(CLK_64),
     .CLK_TAP(net1), .LOAD_INT_B(LOAD_INT_B), .VDD(VDD), .VSS(VSS),
     .D_OUT(SER_OUT), .EXT_RST_B(EXT_RST_B), .LOAD(LOAD));
DelayTap I1 ( .INV_TAP(INV_TAP[2:1]), .EN_TAP(EN_TAP[2:1]),
     .CLK_TAP(net1), .TAP1(TAP1), .VDD(VDD), .VSS(VSS), .TAP2(TAP2),
     .TAP3(TAP3), .D(SER_OUT));

endmodule
// Library - RD53_SER_CML_Bonn, Cell - LoadGen, View - schematic
// LAST TIME SAVED: Mar 15 14:56:09 2017
// NETLIST TIME: Mar 21 20:07:24 2017
`timescale 1ns / 1ps 

module LoadGen ( CLK_WORD, LOAD, VDD, VSS, CLK, RST_B );

output  CLK_WORD, LOAD;

inout  VDD, VSS;

input  CLK, RST_B;

// List of primary aliased buses


specify 
    specparam CDS_LIBNAME  = "RD53_SER_CML_Bonn";
    specparam CDS_CELLNAME = "LoadGen";
    specparam CDS_VIEWNAME = "schematic";
endspecify

NR2XD4 I162 ( net040, net041, net050, VDD, VSS);
DFCNQD4 I199 ( net033, CLK, RST_B, net035, VDD, VSS);
DFCNQD4 I200 ( net050, CLK, RST_B, net033, VDD, VSS);
DFCNQD4 I203 ( clk_div_prebuff, CLK, RST_B, net043, VDD, VSS);
DFCNQD4 I197 ( net037, CLK, RST_B, net039, VDD, VSS);
DFCNQD4 I201 ( net042, CLK, RST_B, clk_div_prebuff, VDD, VSS);
DFCNQD4 I198 ( net035, CLK, RST_B, net037, VDD, VSS);
DFCNQD4 I202 ( net036, CLK, RST_B, LOAD, VDD, VSS);
DFCNQD4 I196 ( net039, CLK, RST_B, clk_mod5, VDD, VSS);
OR2D4 I160 ( net037, net039, net041, VDD, VSS);
OR2D4 I161 ( net033, net035, net040, VDD, VSS);
INVD4 I182 ( clk_div_prebuff, net038, VDD, VSS);
XNR2D4 I206 ( net038, clk_mod5, net042, VDD, VSS);
INVD2 I184 ( net043, net034, VDD, VSS);
AN2D2 I186 ( net034, clk_div_prebuff, net036, VDD, VSS);
INVD12 I185 ( net038, CLK_WORD, VDD, VSS);

endmodule
// Library - RD53_SER_CML_Bonn, Cell - Serializer_TapDelayX4, View -
//schematic
// LAST TIME SAVED: Mar 15 14:56:02 2017
// NETLIST TIME: Mar 21 20:07:24 2017
`timescale 1ns / 1ps 

module Serializer_TapDelayX4 ( CLK_64, CLK_640_INT, LOAD_INT_B, TAP1,
     TAP2, TAP3, VDD, VSS, DATA_SER0, DATA_SER1, DATA_SER2, DATA_SER3,
     EXT_RST_B, SER_CLK, SER_EN_TAP_SER0, SER_EN_TAP_SER1,
     SER_EN_TAP_SER2, SER_EN_TAP_SER3, SER_INV_TAP_SER0,
     SER_INV_TAP_SER1, SER_INV_TAP_SER2, SER_INV_TAP_SER3,
     SER_SEL_OUT_SER0, SER_SEL_OUT_SER1, SER_SEL_OUT_SER2,
     SER_SEL_OUT_SER3 );

output  CLK_64;

inout  VDD, VSS;

input  EXT_RST_B, SER_CLK;

output [3:0]  TAP1;
output [3:0]  LOAD_INT_B;
output [3:0]  TAP3;
output [3:0]  TAP2;
output [3:0]  CLK_640_INT;

input [2:1]  SER_EN_TAP_SER2;
input [2:1]  SER_INV_TAP_SER0;
input [2:1]  SER_INV_TAP_SER2;
input [2:1]  SER_INV_TAP_SER3;
input [2:1]  SER_EN_TAP_SER0;
input [2:1]  SER_EN_TAP_SER3;
input [19:0]  DATA_SER2;
input [19:0]  DATA_SER3;
input [2:1]  SER_EN_TAP_SER1;
input [2:1]  SER_INV_TAP_SER1;
input [1:0]  SER_SEL_OUT_SER0;
input [1:0]  SER_SEL_OUT_SER1;
input [1:0]  SER_SEL_OUT_SER2;
input [1:0]  SER_SEL_OUT_SER3;
input [19:0]  DATA_SER1;
input [19:0]  DATA_SER0;

// Buses in the design

wire  [3:0]  CLK_640_BUF;

wire  [3:0]  CLK_1280_BUF;

wire  [3:0]  LOAD_BUF;

// List of primary aliased buses


specify 
    specparam CDS_LIBNAME  = "RD53_SER_CML_Bonn";
    specparam CDS_CELLNAME = "Serializer_TapDelayX4";
    specparam CDS_VIEWNAME = "schematic";
endspecify

Buff_Tree ClkFastTree ( .Buff12(net06), .Buff11(net04), .Buff(net05),
     .VDD(VDD), .VSS(VSS), .OUT0(CLK_1280_BUF[0]),
     .OUT1(CLK_1280_BUF[1]), .OUT2(CLK_1280_BUF[2]),
     .OUT3(CLK_1280_BUF[3]), .IN(CLK_1280));
Buff_Tree ClkTree ( .Buff12(net03), .Buff11(net015), .Buff(net012),
     .VDD(VDD), .VSS(VSS), .OUT0(CLK_640_BUF[0]),
     .OUT1(CLK_640_BUF[1]), .OUT2(CLK_640_BUF[2]),
     .OUT3(CLK_640_BUF[3]), .IN(CLK_640));
Buff_Tree LoadTree ( .Buff12(net010), .Buff11(net08), .Buff(net09),
     .VDD(VDD), .VSS(VSS), .OUT0(LOAD_BUF[0]), .OUT1(LOAD_BUF[1]),
     .OUT2(LOAD_BUF[2]), .OUT3(LOAD_BUF[3]), .IN(LOAD));
CKND4 I24 ( net018, net07, VDD, VSS);
DFQD4 I8 ( .CP(CLK_1280), .D(net07), .Q(net018), .VDD(VDD),
     .VSS(VSS));


// initial begin
   // $deposit( I8.D, 1'b0 ) ;
// end


Serializer_TapDelay Ser[3:0] ( .CLK_640_INT(CLK_640_INT[3:0]),
     .LOAD_INT_B(LOAD_INT_B[3:0]), .TAP1(TAP1[3:0]), .TAP2(TAP2[3:0]),
     .TAP3(TAP3[3:0]), .VDD(VDD), .VSS(VSS), .CLK_64(CLK_64),
     .CLK_640(CLK_640_BUF[3:0]), .DATA({DATA_SER3[19:0],
     DATA_SER2[19:0], DATA_SER1[19:0], DATA_SER0[19:0]}),
     .EN_TAP({SER_EN_TAP_SER3[2:1], SER_EN_TAP_SER2[2:1],
     SER_EN_TAP_SER1[2:1], SER_EN_TAP_SER0[2:1]}),
     .EXT_RST_B(EXT_RST_B), .INV_TAP({SER_INV_TAP_SER3[2:1],
     SER_INV_TAP_SER2[2:1], SER_INV_TAP_SER1[2:1],
     SER_INV_TAP_SER0[2:1]}), .LOAD(LOAD_BUF[3:0]),
     .SER_CLK(CLK_1280_BUF[3:0]), .SER_SEL_OUT({SER_SEL_OUT_SER3[1:0],
     SER_SEL_OUT_SER2[1:0], SER_SEL_OUT_SER1[1:0],
     SER_SEL_OUT_SER0[1:0]}));
LoadGen I2 ( .CLK_WORD(CLK_64), .RST_B(EXT_RST_B), .CLK(CLK_640),
     .LOAD(LOAD), .VDD(VDD), .VSS(VSS));
CKBD12 I58 ( SER_CLK, CLK_1280, VDD, VSS);
CKBD12 I57 ( net018, CLK_640, VDD, VSS);

endmodule


// End HDL models
