Top:
  RxPhy[:]:
    ###################################
    ###     Synchronous Front End   ###
    ###################################  
    IBIASP1_SYNC: 100
    IBIASP2_SYNC: 150
    IBIAS_SF_SYNC: 100
    IBIAS_KRUM_SYNC: 40 # Default=140
    IBIAS_DISC_SYNC: 300 # Default=200
    ICTRL_SYNCT_SYNC: 100
    VBL_SYNC: 400 # Default=450
    VTH_SYNC: 300
    VREF_KRUM_SYNC: 450 # Default=490
    AutoZero: 0
    SelC2F: 1
    SelC4F: 0
    FastToT: 0
    ###############################
    ###     Linear Front End    ###
    ###############################
    PA_IN_BIAS_LIN: 300
    FC_BIAS_LIN: 20
    KRUM_CURR_LIN: 50
    LDAC_LIN: 130 # Default=80
    COMP_LIN: 110
    REF_KRUM_LIN: 300
    Vthreshold_LIN: 400 # Default=408
    #####################################        
    ###     Differential Front End    ###
    #####################################     
    PRMP_DIFF: 500 # Default=533
    FOL_DIFF: 500 # Default=542
    PRECOMP_DIFF: 400 # Default=551
    COMP_DIFF: 1000 # Default=528
    VFF_DIFF: 50 # Default=164
    VTH1_DIFF: 250 # Default=1023
    VTH2_DIFF: 50 # Default=0
    LCC_DIFF: 20
    LccEn: 0 # Default=1
    AddFeedbackCap: 0 
    #################################
    ###     Power Supply Rails    ###
    #################################    
    SLDO_ANALOG_TRIM: 26 # Default=16 
    SLDO_DIGITAL_TRIM: 20 # Default=16 
    #############################
    ###     Digital Matrix    ###
    #############################    
    EN_CORE_COL_SYNC: 0xFFFF
    EN_CORE_COL_LIN_1: 0xFFFF
    EN_CORE_COL_LIN_2: 1
    EN_CORE_COL_DIFF_1: 0xFFFF # Default=0xFF
    EN_CORE_COL_DIFF_2: 1
    LATENCY_CONFIG: 64 # Default=500
    WR_SYNC_DELAY_SYNC: 16
    ###############################
    ###         Injection       ###
    ###############################    
    InjAnaMode: 0
    InjEnDig: 0 # Default=1
    InjDelay: 0
    VCAL_HIGH: 1000 # Default=500
    VCAL_MED: 1000 # Default=300
    CAL_COLPR_SYNC[:]: 0xFFFF
    CAL_COLPR_LIN[:]: 0xFFFF
    CAL_COLPR_LIN5: 0xF
    CAL_COLPR_DIFF[:]: 0xFFFF
    CAL_COLPR_DIFF5: 0xF
    #########################
    ###         I/O       ###
    #########################
    DEBUG_CONFIG: 0
    DataReadDelay: 0
    OutputSerType: 0
    ActiveLanes: 0xF # Default=1
    OutputFormat: 0
    JTAG_TDO: 0
    STATUS_EN: 1
    STATUS_DS: 0
    LANE0_LVDS: 1
    LANE0_LVDS_BIAS: 0
    GP_LVDS_EN: 0
    GP_LVDS_BIAS: 4
    GP_LVDS_ROUTE: 0
    CDR_SEL_DEL_CLK: 0
    CDR_PD_SEL: 0
    CDR_PD_DEL: 8
    CDR_EN_GCK2: 0
    CDR_VCO_GAIN: 3
    CDR_SEL_SER_CLK: 3 # Default=0
    VCO_BUFF_BIAS: 400
    CDR_CP_IBIAS: 50
    VCO_IBIAS: 500
    SER_SEL_OUT[:]: 1
    CmlInvTap: 0
    CmlEnTap: 1 # Default=3
    CmlEn: 0xF
    CML_TAP_BIAS[0]: 600 # Default=500
    CML_TAP_BIAS[1]: 0
    CML_TAP_BIAS[2]: 0
    AuroraCcWait: 25
    AuroraCcSend: 3
    AuroraCbWaitLow: 15
    AuroraCbSend: 0
    AuroraCbWaitHigh: 15
    AURORA_INIT_WAIT: 32
    MON_FRAME_SKIP: 200 # Default=50
    AUTO_READ_A[0]: 136
    AUTO_READ_B[0]: 130
    AUTO_READ_A[1]: 118
    AUTO_READ_B[1]: 119    
    AUTO_READ_A[2]: 120
    AUTO_READ_B[2]: 121
    AUTO_READ_A[3]: 122
    AUTO_READ_B[3]: 123    
    ###################################################
    ###         Test and Monitoring Functions       ###
    ###################################################
    MonitorEnable: 0    
    MonitorImonMux: 63 
    MonitorVmonMux: 127 
    HITOR_MASK_SYNC[:]: 0 
    HITOR_MASK_LIN1[:]: 0 
    HITOR_MASK_LIN2[:]: 0 
    HITOR_MASK_DIFF1[:]: 0 
    HITOR_MASK_DIFF2[:]: 0 
    AdcRefTrim: 0 
    AdcTrim: 0 
    SENSOR_CONFIG[:]: 0 
    RING_OSC_ENABLE: 0 
    RING_OSC[:]: 0 
    BC_CTR: 0 
    TRIG_CTR: 0 
    LCK_LOSS_CTR: 0 
    BFLIP_WARN_CTR: 0 
    BFLIP_ERR_CTR: 0 
    CMD_ERR_CTR: 0 
    FIFO_FULL_CTR[:]: 0 
    AI_PIX_COL: 0 
    AI_PIX_ROW: 0 
    HitOr_Cnt[:]: 0 
    SKP_TRIG_CNT: 0 
    ERR_MASK: 0 
